runtime: custom
env: flex
service: load-generator-app
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always
health_check:
  enable_health_check: False
